variables:
  RULES_CHANGES_PATH: "*/"
  FRONTEND_PATH: "frontend/"
  BACKEND_PATH: "backend/digitalbooking"


stages:
- build
- test 
- deploy


.base-rules:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push"'
          changes:
            - $RULES_CHANGES_PATH
        - when: always
          allow_failure: true

.backend:
    extends: .base-rules
    variables:
        RULES_CHANGES_PATH: "backend/*/"

.frontend: 
    extends: .base-rules
    variables:
        RULES_CHANGES_PATH: "frontend/*/"

backend-build:
    image: maven:3-openjdk-17
    stage: build
    extends: .backend
    needs: []
    script:
        - echo "Building backend"
        - "cd backend/digitalbooking"
        - "mvn clean package"
    artifacts: 
        paths:
        - $BACKEND_PATH

