variables:
  RULES_CHANGES_PATH: "*/"
  FRONTEND_PATH: "frontend"
  BACKEND_PATH: "backend/digitalbooking"


stages:
- build
- test 
- deploy


.base-rules:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push"'
          changes:
            - $RULES_CHANGES_PATH
        - when: always
          allow_failure: true

.backend:
    extends: .base-rules
    variables:
        RULES_CHANGES_PATH: "backend/*/"

.frontend: 
    extends: .base-rules
    variables:
        RULES_CHANGES_PATH: "frontend/*/"

backend-build:
    image: maven:3-openjdk-17
    stage: build
    extends: .backend
    needs: []
    script:
        - echo "Building backend"
        - "cd backend/digitalbooking"
        - "mvn clean package"
    artifacts: 
        paths:
        - $BACKEND_PATH/target/*.jar

frontend-build:
    image: node:16.14.2-alpine
    stage: build
    extends: .frontend
    needs: []
    script: 
        - echo "Building frontend"
        - cd frontend
        - npm install
        - CI=false npm run build
        - echo "Compile Complete!!!"
    
    artifacts:
        paths:
         - frontend/dist

backend-test:
    stage: test
    extends: .backend
    needs: ["backend-build"]
    script: 
        - echo "Testing backend"
    artifacts:
        paths:
        - $BACKEND_PATH/target/*.jar

frontend-test: 
  stage: test 
  extends: .frontend  
  needs: ["frontend-build"]
  script:
    - echo "Test of Frontend..."
  artifacts:
    paths:
    - frontend/dist

backend-deploy:
  stage: deploy
  image: alpine:3.11
  extends: .backend
  needs: ["backend-test"]
  before_script:
    - apk update && apk add openssh-client bash
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$UBUNTU_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-keyscan -H $UBUNTU_DEPLOY_SERVER_BA_IP >> ~/.ssh/known_hosts
    - echo "nohup java -jar /home/ubuntu/digitalbooking-0.0.1-SNAPSHOT.jar > output.log 2>&1 &" > start-app.sh
    - chmod +x start-app.sh
    - scp start-app.sh ubuntu@$UBUNTU_DEPLOY_SERVER_BA_IP:/home/ubuntu/ 
  script:
    - echo "Deploying..."
    - scp $BACKEND_PATH/target/*.jar ubuntu@$UBUNTU_DEPLOY_SERVER_BA_IP:/home/ubuntu/
    - ssh ubuntu@$UBUNTU_DEPLOY_SERVER_BA_IP 'pkill java|| echo "No hay proceso java corriendo"'
    - ssh ubuntu@$UBUNTU_DEPLOY_SERVER_BA_IP '/home/ubuntu/start-app.sh'

frontend-deploy: 
  image: python:latest
  stage: deploy
  extends: .frontend
  needs: ["frontend-test"]
  script:
    - echo "Deploying into Front..."
    - pip install awscli
    - aws --version
    - aws configure set aws_acces_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_acces_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync frontend/dist/ s3://airc2c.com --delete
    
