production_deployment:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws s3 rm --recursive s3://$AWS_BUCKET/
    - aws s3 cp ./site s3://$AWS_BUCKET/ --recursive
  only:
    - master

