variables:
  RULES_CHANGES_PATH: "*/"
  FRONTEND_PATH: "frontend/"
  BACKEND_PATH: "backend/digitalbooking"


stages:
- build
- test 
- deploy


.base-rules:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push"'
          changes:
            - $RULES_CHANGES_PATH
        - when: always
          allow_failure: true

.backend:
    extends: .base-rules
    variables:
        RULES_CHANGES_PATH: "backend/*/"

.frontend: 
    extends: .base-rules
    variables:
        RULES_CHANGES_PATH: "frontend/*/"

backend-build:
    image: maven:3-openjdk-17
    stage: build
    extends: .backend
    needs: []
    script:
        - echo "Building backend"
        - "cd backend/digitalbooking"
        - "mvn clean package"
    artifacts: 
        paths:
        - $BACKEND_PATH/*.jar

frontend-build:
    image: node:16.13.1-alpine3.15
    stage: build
    extends: .frontend
    needs: []
    script: 
        - echo "Building frontend"
        - cd $FRONTEND_PATH
        - npm i --legacy-peer-deps
        - npm run prod
    artifacts:
        paths:
        - $FRONTEND_PATH
