// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC16FooterResponsiveDesktopTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC16FooterResponsiveDesktop() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    {
      WebElement element = driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p")).click();
    driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p")).click();
    driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F")).click();
    driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F")).click();
    driver.findElement(By.cssSelector(".Social_social__PfZlE:nth-child(2) > a:nth-child(1) > img")).click();
    driver.findElement(By.cssSelector(".Social_social__PfZlE:nth-child(2) > a:nth-child(2) > img")).click();
    driver.findElement(By.cssSelector(".Social_social__PfZlE:nth-child(2) > a:nth-child(3) > img")).click();
    driver.findElement(By.cssSelector(".Social_social__PfZlE:nth-child(2) > a:nth-child(4) > img")).click();
    driver.findElement(By.cssSelector(".Header_containerLeft__oHfYf img")).click();
    driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p")).click();
    driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F")).click();
    driver.findElement(By.cssSelector(".Social_social__PfZlE:nth-child(2) > a:nth-child(1) > img")).click();
    driver.findElement(By.cssSelector(".Social_social__PfZlE:nth-child(2) > a:nth-child(2) > img")).click();
    driver.findElement(By.cssSelector(".Social_social__PfZlE:nth-child(2) > a:nth-child(3) > img")).click();
    driver.findElement(By.cssSelector(".Social_social__PfZlE:nth-child(2) > a:nth-child(4) > img")).click();
    driver.findElement(By.cssSelector(".Header_containerLeft__oHfYf img")).click();
    driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p")).click();
    driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p")).click();
    driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".Footer_footerContainer__eqp8F > p"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.close();
  }
}
